---
version: "3"
services:
  influxdb:
    image: influxdb:2.1.1
    container_name: influxdb
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086

  telegraf:
    image: telegraf:1.19
    container_name: telegraf
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    restart: on-failure:10
    depends_on:
      - influxdb
  
  dht:
    container_name: dht
    depends_on:
      - telegraf
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_dht
    devices:
      - /dev/gpiomem:/dev/gpiomem
    privileged: true
    restart: on-failure:10
    env_file:
      - .env

  grafana:
    image: grafana/grafana-oss:8.4.3
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana:rw
    depends_on:
      - influxdb
    restart: on-failure:10
    ports:
      - ${GRAFANA_PORT}:3000

volumes:
  influxdb-storage:
  grafana-storage: