FROM python:3.9.2

WORKDIR /dht22

COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY dht22/ .
RUN chmod u+x ./*.py
ENTRYPOINT [ "python3", "dht22_vcgencmd.py"]